### ISSUE TITLE
Cross-Referencing APIs not working with multiple Serverless files

### ISSUE THREAD

**Issue by Borduhh** [AnomalyInnovations/serverless-stack-demo-ext-api#23]
Working with the tutorial here: https://serverless-stack.com/chapters/share-an-api-endpoint-between-services.html

However even after adding the following export:

```
resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiRootResourceId
```

and the following import: 
```
 apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId
```

I still get the same error from all three APIs who are trying to reference the already existing API.
```
 Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template
      at /tmp/seed/source/apis/saascharge/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/tmp/seed/source/apis/saascharge/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

Steps I have taken to debug:

1. Verified that the export is being deployed prior to the import
![Screen Shot 2020-10-06 at 5 43 15 PM](https://user-images.githubusercontent.com/4759596/95263220-73727a00-07fb-11eb-9d69-d5d293646099.png)

2. Verified that the syntax matches the tutorial above.

3. Verified that the correct variables are being exported:
![Screen Shot 2020-10-06 at 5 46 15 PM](https://user-images.githubusercontent.com/4759596/95263512-e11ea600-07fb-11eb-818c-ea9ce843f67f.png)

Is this tutorial just out of date? Any nudges in the right direction would be greatly appreciated.

**Comment by jayair** [comment]
You might need to update Serverless Framework. Which version are you using?
