### ISSUE TITLE
./startServer -> Error: Cannot find module 'http-proxy'

### ISSUE THREAD

**Issue by StErMi** [AnomalyInnovations/serverless-stack-demo-ext-api#7]
I've just done a fresh install with `npm install` and tried to launch the local server with the `./startServer` but I got this error:

```
$ ./startServer 
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'http-proxy'
Require stack:
- C:\Users\stermi\dev\workspace_serverless\serverless-stack-demo-ext-api\startServer      
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\stermi\dev\workspace_serverless\serverless-stack-demo-ext-api\startServer:5:19)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
```

how can I fix it?

**Comment by jayair** [comment]
Hmm it looks like it's missing in the `package.json`. I think it should be a dev dependency. Can you try it and submit a PR?

**Comment by StErMi** [comment]
@jayair sorry, I didn't update the GitHub issue. After installing the dev dependency I get this error:

```
$ ./startServer
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn serverless ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:58:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:17:11
```

**Comment by AlexSun98** [comment]
any update pls? @StErMi

**Comment by StErMi** [comment]
not at the moment :(

**Comment by jayair** [comment]
@AlexSun98 You should be able to use serverless-offline as is but the `startServer` script is just for convenience to run all the services together.
